### ISSUE TITLE
Create a less branded printing experience for the checklist

### ISSUE THREAD

**Issue by vikeen** [karllhughes/side-project-marketing#10]
## Problem
I love the checklist and wanted to print it off to add to my daily habit tracker, but the printable page contained the email list signup which is not ideal for printing in my opinion. I then went through a few hurdles and converted the checklist to a [google doc](https://docs.google.com/document/d/1KjENoss6AqanVnuIk2U1Xtnsc8upcfgAgAY-2DsIzfg/edit?usp=sharing), but that won't stay updated so I don't like it either.

### Printing Images
<img width="691" alt="screen shot 2017-08-08 at 11 27 55 am" src="https://user-images.githubusercontent.com/1700158/29083017-ee94098c-7c2c-11e7-8a51-11d7305fa4a6.png">
<img width="592" alt="screen shot 2017-08-08 at 11 28 04 am" src="https://user-images.githubusercontent.com/1700158/29083019-f0bee8a8-7c2c-11e7-86e8-ffbe35a108ed.png">

## Solution
Add a printing stylesheet that removes the email list and trims down any unnecessary text. I am willing to pull the repo down and do this work, but I wanted to confirm that it's worth doing in your opinion.

**Comment by karllhughes** [comment]
I totally support this. The easiest workaround would be to get the raw markdown file: https://raw.githubusercontent.com/karllhughes/side-project-marketing/master/marketing-checklist.md

And paste it into [Gist like this](https://gist.github.com/karllhughes/aa90cc83d63ea70fbdc85a44c9dec265).

But, I have no problem also providing a more "printer-friendly" downloadable version. If you want to take a stab at it, feel free!

**Comment by vikeen** [comment]
How would you keep the gist updated?

**Comment by karllhughes** [comment]
@vikeen I think that's the weakness of the workaround for now.

I like the idea of a "printable" page on the site though. If you haven't worked with Jekyll, I'd be happy to create a version of that in the next week or so. Let me know!

**Comment by vikeen** [comment]
@karllhughes, no worries. I'll take a swing at it this evening or tomorrow.

**Comment by karllhughes** [comment]
Closed #14
