### ISSUE TITLE
Add list of survey tools

### ISSUE THREAD

**Issue by karllhughes** [karllhughes/side-project-marketing#11]
I'd like to add a list of customer/prospect survey tools. I haven't done much of this, but I've heard of some:

- [Google Consumer Surveys](https://www.google.com/analytics/surveys/)
- [Google Forms](https://www.google.com/forms/about/)
- [Wufoo Forms](https://www.wufoo.com/gallery/templates/surveys/)
- [SurveyMonkey](https://www.surveymonkey.com/)

I welcome any additional suggestions here.

**Comment by vikeen** [comment]
I've used typeform and loved it. https://www.typeform.com/

**Comment by feliperomero3** [comment]
What about the Open Source [LimeSurvey](https://github.com/LimeSurvey/LimeSurvey)

**Comment by emanuelb** [comment]
* https://www.tellform.com/

**Comment by niko001** [comment]
- http://www.ideacheck.io also takes care of finding respondents for your survey

**Comment by karllhughes** [comment]
Thanks for your input everyone. I just published a new post with all your suggestions: https://www.sideprojectchecklist.com/2017/survey-tools/

As more roll in, I'll be sure to keep the post updated.

**Comment by chriscarvalho** [comment]
Hi Karl,

Really enjoying your posts! I'd love to chat with you more about getting MicroHero added to the list (www.microhero.com/surveys)

Thanks,

Chris

**Comment by karllhughes** [comment]
@chriscarvalho added!

**Comment by pelmenept** [comment]
Hi!, I am a founder of Insight Stash - https://insightstash.com it would be awesome if you consider including us on your list of survey tools!

thanks!

Stan

**Comment by karllhughes** [comment]
@pelmenept adding now, thanks!

**Comment by pelmenept** [comment]
@karllhughes Thank you! I think the page is down now :)

**Comment by karllhughes** [comment]
New survey tools should be added via this Airtable form: https://airtable.com/shrwrPOxd0wlqoiZb

Thanks for your contributions!
