### ISSUE TITLE
Improve the list of landing page creation tools

### ISSUE THREAD

**Issue by karllhughes** [karllhughes/side-project-marketing#12]
I know there are hundreds if not thousands of free and low-cost options for building landing pages, but I've only tried a few. I'd like to include a more comprehensive list, but so far all I have is:

- Unbounce
- Squarespace
- Rocketpages
- Launchrock
- Github Pages and Jekyll
- Carrd

Please, include your suggestions here so we can add them to the [Side Project Landing Page List](https://www.sideprojectchecklist.com/marketing-checklist/#landing-page). Thanks!

**Comment by jonathanlurie** [comment]
The creator of Carrd ([@ajlkn](https://twitter.com/ajlkn)) also gives all his templates for free at [html5up.net](http://html5up.net). Very convenient for a side with a Github page (possibly as a GitHub org, to have a project-oriented URL)

**Comment by niallie** [comment]
Thrive Themes make a suite of Wordpress themes and plugins that are very focused on creating landing pages and conversion optimisation.

**Comment by karllhughes** [comment]
- Clickfunnels: https://www.clickfunnels.com/
- Woobox: https://woobox.com/
- Leadpages: https://www.leadpages.net/

**Comment by emanuelb** [comment]
* GitLab pages: https://about.gitlab.com/2016/04/07/gitlab-pages-setup/
* Neocities: https://neocities.org/

**Comment by karllhughes** [comment]
Thanks for all the suggestions! I've compiled them in this blog post, and plan on keeping it updated as new suggestions roll in: https://www.sideprojectchecklist.com/2017/landing-page-tools/

**Comment by scottweisman** [comment]
Lanchaco has a really nice (and free) landing page builder: http://launchaco.com/build/

**Comment by aiv55** [comment]
Hello @karllhughes! Great list, but it's mainly DIY tools and missing services that create landing pages for you. These services are a better fit for founders who don't have enough time for a DIY tool:
- https://www.reverentpages.com/
- https://www.mopro.com/
- http://landing-page-experts.com/

Obviously you can't be expected to list every company that offers landing pages as a service, but I think what makes these unique is that they either do landing pages exclusively or they deliver websites in a completely automated way. What do you think?

**Comment by karllhughes** [comment]
@aiv55 @scottweisman thanks for the suggestions! Adding them to the blog post now.

**Comment by karllhughes** [comment]
Another one came in: http://landinglion.com/

**Comment by rkeppner** [comment]
Just ran across another one: https://landingi.com/

I only noticed because AppSumo is promoting them right now...

**Comment by yanivgoldenberg** [comment]
Free Page Builder for WordPress: https://elementor.com/

**Comment by karllhughes** [comment]
New landing page tools should be added via this Airtable form: https://airtable.com/shrwrPOxd0wlqoiZb

Thanks for your contributions!
