### ISSUE TITLE
List of Email Marketing Tools

### ISSUE THREAD

**Issue by karllhughes** [karllhughes/side-project-marketing#13]
I included a short list of email list management and sending tools in the first iteration of the marketing checklist, but now I'm looking for suggestions to improve it.

So far the list is just:

- Buttondown
- Constant Contact
- FreshMail
- Mad Mimi
- Mailchimp
- Mailjet

What did I miss? Add your suggestions here so I can update the [list of email marketing tools for side projects](https://www.sideprojectchecklist.com/marketing-checklist/#email-setup).

**Comment by bjorntheart** [comment]
Hey, Karl.

Here's one: https://www.drip.co/

**Comment by christianbaer** [comment]
I really like https://sumo.com/ for getting more subscribers / leads.

**Comment by benhomie** [comment]
Definitely [Sendy](https://sendy.co)! Self hosted email marketing tool that sends emails via Amazon SES, very suitable for startups. Recently just released a major update version 3.0.

**Comment by jonathanlurie** [comment]
[mailgun.com](http://mailgun.com) is good alternative (10k emails/month with free account) and I like that they have a simple API, so it's very "developer friendly".

**Comment by karllhughes** [comment]
Another one I ran into: https://charley.io/

**Comment by karllhughes** [comment]
More suggested via email: 

- ConvertKit: https://convertkit.com/
- Aweber: https://www.aweber.com/
- Mautic: https://www.mautic.org/

**Comment by palash76** [comment]
Those who have tried Retainly [email marketing software](https://retainly.co) are just loving it.

**Comment by karllhughes** [comment]
Thanks all! I've compiled the list into a new blog post: https://www.sideprojectchecklist.com/2017/email-marketing-tools/

And in the checklist, I've linked to that blog post. This helps keep the checklist succinct while offering more information for people who want to dig in.

I'm keeping this issue open so that we can continue to improve the list as new suggestions come in.

**Comment by ailith** [comment]
Hey Karl, how about [Revue](https://www.getrevue.co)? I'm using it for Remoteur, so far so good!

**Comment by karllhughes** [comment]
Will add it next week in my update. Thanks!

**Comment by webbie917** [comment]
[BigMailer.io](https://www.bigmailer.io/plans-and-pricing/) has a generous, startup-friendly free tier - up to 5K contacts (2k is a typical limit for big names). It runs on Amazon SES and has built-in brand management (for all your side projects!) and multi-optin management that many market leaders lack. Supports marketing campaigns now, but automation is in the works and coming soon!

**Comment by lucasverra** [comment]
Hubspot marketing is the non-free solution to be paired with it's **free** for real crm (and VERY capable)

**Comment by karllhughes** [comment]
@lucasverra @webbie917 @ailith added your suggestions today. Thanks!

**Comment by karllhughes** [comment]
New email marketing tools should be added via this Airtable form: https://airtable.com/shrwrPOxd0wlqoiZb

Thanks for your contributions!
