### ISSUE TITLE
Options for live chat

### ISSUE THREAD

**Issue by karllhughes** [karllhughes/side-project-marketing#19]
After @hengwoon [suggested we add a section on live chat](https://github.com/karllhughes/side-project-marketing/pull/15), I've been keeping an eye out for alternative tools and services.

So far I have:

- Autopilot
- Chatra
- Crisp.chat
- HelpCrunch
- Intercom
- Reamaze

What else have you tried? Any recommendations?

**Comment by karllhughes** [comment]
Found some more from a friend here: https://docs.google.com/spreadsheets/d/1xS-aINZbEQZUK-bU7Yx5UOEnWPpxSe8mKWslEbgNPZM/edit

**Comment by karllhughes** [comment]
Published here: https://www.sideprojectchecklist.com/2017/customer-chat-tools/

**Comment by laughedelic** [comment]
[Gitter](https://gitter.im/)? It also has some [widget](https://sidecar.gitter.im/).

**Comment by atherdon** [comment]
@karllhughes what do you think about adding notes, like (paid, free-plan-exists) to website page?
It'll be a good advantage. On start i'll look on free tool, on different projects.

Don't know about gitter widget. Thanks @laughedelic

**Comment by karllhughes** [comment]
@laughedelic I think Gitter could qualify. It's a bit different but could be used similarly.

@atherdon yes! That would be really helpful. I didn't spend a ton of time researching these but if you come up with any pricing data and want to share it that would be fantastic.

**Comment by dmgawel** [comment]
I'd like to recommend two more live chat solutions:

* [LiveChat Inc](https://www.livechatinc.com) — The Live Chat :-) Full featured (with tickets system, etc.). It's way cheaper than i.e. Intercom and has 30-day free trial.
* [Chat.io](https://www.chat.io) — not so featured as LiveChat but has a Facebook integration that let's you handle Messenger conversations along with chats from website in just one app. No plans, 10$/month, 14-day free trial.

Disclaimer: I'm Web Developer at LiveChat ;-)

**Comment by karllhughes** [comment]
Thanks @dmgawel added your suggestions today.

**Comment by lucasverra** [comment]
i've tested https://www.tawk.to/ like 2 years ago, free version worked good enough for a non monetized project. Do not know today, do not know with pro "i want to pay" features needed. Mobile apps & web dashboard included  👍 

>Rich in Features and still 100% FREE !
All the premium features you would expect, just without the price tag.
There is no 'premium' version, just one feature packed version for everyone.

> How can you offer this for free?
Currently we generate revenue by providing live answering services for a select group of customers - though to use the software yourself is completely free, with no limits at all on the number of Agents, Chat Volumes or sites that you can add widgets to. It's truly 100% free.

**Comment by karllhughes** [comment]
@lucasverra awesome! I'm adding that now.

**Comment by atherdon** [comment]
I think this must be included too. 
SmallChat https://small.chat/pricing
Not tested it yet, but will try later.

**Comment by Chippd** [comment]
@atherdon testing that now in a side project of mine, so far a really nice integration and the free plan seems more than fair.

**Comment by atherdon** [comment]
@Chippd when I was diggin into this topic(free chat tools), I've met the drift, and for now, it's work well for me, you also can put one widget and manage a few websites from one account(this is what they told me). But I think It will be better to manage all discussions into my slack account, so I'll look for other solutions and if i'll find another "0" price tool - I'll add it to this thread. 

Btw, smallchat will be the first tool to test in future.

I also find a cool lifehack: create a separate channel for each sideproject you have and just put link in header :) maybe this can save a lot of time for someone

Btw, @karllhughes maybe it'll be a good feature to add a voting system for each tool in future?

**Comment by karllhughes** [comment]
@atherdon I'll look into that. I'd definitely be interested in making the lists of tools more interactive, and voting makes a lot of sense.

In the mean time, adding the new suggestions this week. Thanks!

**Comment by atherdon** [comment]
i find a lot of data for you @karllhughes 
https://siftery.com/categories/support/live-chat

**Comment by karllhughes** [comment]
@atherdon that's a cool site! I'm going to take a deeper look and add some. Thanks for sharing.

**Comment by karllhughes** [comment]
New live chat tools should be added via this Airtable form: https://airtable.com/shrwrPOxd0wlqoiZb

Thanks for your contributions!
