### ISSUE TITLE
Tools for Finding/researching competition

### ISSUE THREAD

**Issue by karllhughes** [karllhughes/side-project-marketing#22]
I've got a short list on the checklist now, but would like to expand it.

What tools do you use to find or research your competition?

**Comment by karllhughes** [comment]
Published: https://www.sideprojectchecklist.com/2017/competition-tools/

**Comment by ryanwi** [comment]
[ScoutZen](https://www.scoutzen.com) provides a couple ways to research competitors. Scouts can be created to track a competitor's followers/following on Twitter, as well as to monitor for mentions of your competition with automated advanced Twitter searches.

(Disclaimer, I'm part of the ScoutZen team)

**Comment by karllhughes** [comment]
New competitive research tools should be added via this Airtable form: https://airtable.com/shrwrPOxd0wlqoiZb

Thanks for your contributions!
