### ISSUE TITLE
404 error for icon attribution in footer

### ISSUE THREAD

**Issue by taprun** [karllhughes/side-project-marketing#24]
The link in the footer for "Madebyoliver" leads to a 404.

**Comment by karllhughes** [comment]
Thanks for pointing this out. I'll try to find the right link and update it!

**Comment by taprun** [comment]
This is my guess: http://madebyoliver.com

**Comment by karllhughes** [comment]
It looks like the author name changed on Flaticon: https://www.flaticon.com/free-icon/idea_148819

I've updated the footer. Thanks for pointing this out @taprun!
