### ISSUE TITLE
Keyword research tools

### ISSUE THREAD

**Issue by karllhughes** [karllhughes/side-project-marketing#32]
A lot of SEO people recommend researching keywords and intentionally creating content that will help you rank for them. I'm compiling a list of these keyword research tools, but so far [it's pretty short](https://www.sideprojectchecklist.com/marketing-checklist/#keyword-research-tools). If you know of any others, let me know!

**Comment by jonathanmillspatrick** [comment]
I recently bought a lifetime license for SerpStat's basic solution for $47. Well worth the purchase.

**Comment by AnnaTiana** [comment]
Hello, I use [SERPstat](https://serpstat.com/) - growth hacking tool for SEO, PPC and content marketing.
