### ISSUE TITLE
Blogging platform suggestions

### ISSUE THREAD

**Issue by fartattorney** [karllhughes/side-project-marketing#33]
Might be too simple for some, but [Write.as](https://write.as) is quick, free (or cheap to upgrade), does custom domains, custom CSS, and it's easy to create a bunch of blogs from one account if you upgrade. It's all we need, so we use it on all our small projects.

**Comment by karllhughes** [comment]
Will add this next week. Thanks @fartattorney!

PS: Awesome username.

**Comment by fartattorney** [comment]
Haha :grin: thanks @karllhughes

**Comment by karllhughes** [comment]
@fartattorney I added your suggestion just now. I'm going to leave this issue open for any future suggestions for blogging platforms though. Thanks again!

**Comment by ghost** [comment]
@karllhughes - 

Medium, Drupal, Wordpress, Squarespace are all blogging platforms. Most have paid/unpaid versions and very minimalist templates.

**Comment by karllhughes** [comment]
@lizkrupka Medium, Wordpress, and Squarespace are already in the article: https://www.sideprojectchecklist.com/2017/blogging-platforms/

But I'll add Drupal next week. Great suggestion, and as a PHP dev, I can't believe I missed it!

**Comment by karllhughes** [comment]
New blogging platforms should be added via this Airtable form: https://airtable.com/shrwrPOxd0wlqoiZb

Thanks for your contributions!
