### ISSUE TITLE
CRM suggestions

### ISSUE THREAD

**Issue by lucasverra** [karllhughes/side-project-marketing#35]
First and free 

Hubspot free crm. The catch is that they lure you in with very decent software and then they want you to pay for mail automation. CRM is good and can be used without mail automation

**Comment by karllhughes** [comment]
@lucasverra I haven't started collecting CRM software or a lot of sales-related information because I know so little about sales. I'd be interested in heading in that direction though.

Do you know of any other CRM's that are good? I have worked at companies that used Salesforce, Pipedrive, and even Trello as a simple CRM.

**Comment by lucasverra** [comment]
I've been a salesforce admin and for sure salesforce is a very capable and complex machine. Price is steep ~100us /month*rep

**Comment by ghost** [comment]
I think alot of it depends on database size and how many users you have that want to be able to access the CRM. Salesforce is a beast and it can do whatever you want it to do, the biggest portion about it is that it's expensive if you're not going to utilize it's full capabilities and functionalities. 

Some marketing automation softwares that are smaller like myEmma, HubSpot, even MailChimp etc. Could be a CRM until you're a bigger dog and are going to really utilize it.

**Comment by karllhughes** [comment]
@lizkrupka agreed.

When making list posts, I don't mind including _some_ large, expensive software services (especially if they have a free/cheap tier), but the bulk should be affordable enough for a side project.

I haven't gotten to a point where I need a real CRM yet (spreadsheets and mail lists are good enough), but I've worked for companies that have used them.

**Comment by ghost** [comment]
That would be something really awesome if some of the bigger softwares would let you be able to do.

I'd love to practice more Eloqua but it's like impossible to afford that as an individual. I wish you could buy a single user instance at an affordable price to just practice. 

#rant

**Comment by atherdon** [comment]
Hi @karllhughes, I'm thinking that this posts will be helpful for you:
(yes, it has duplicates, but I want to share all of them an avoid missing something)

1. https://www.producthunt.com/ask/1447-what-s-the-best-personal-free-crm-service
2. https://www.producthunt.com/ask/1864-what-is-the-best-and-not-so-hard-on-the-wallet-free-crm-why
3. https://www.producthunt.com/ask/1306-what-s-a-great-small-business-email-open-tracking-crm-under-10-mo
4. https://www.producthunt.com/ask/1978-what-s-the-best-crm-for-a-small-medium-size-business-out-there
5. https://www.producthunt.com/ask/4365-what-s-the-best-crm-for-a-small-startup

Btw, Hubspot Sales is my favorite. Free and have most needed features

**Comment by karllhughes** [comment]
@atherdon this is awesome. Thanks for putting these together. I'll look the lists over and add them to an upcoming blog post.

**Comment by karllhughes** [comment]
Another one: https://www.infusionsoft.com

**Comment by ghost** [comment]
I found this one over the weekend - would be great for small businesses: https://highrisehq.com/about/

**Comment by karllhughes** [comment]
I put together a list available here: https://www.sideprojectchecklist.com/2017/crm-side-projects/

You can continue to submit suggestions here by selecting the category "CRM": https://airtable.com/shrwrPOxd0wlqoiZb

Thanks for all the suggestions!
