### ISSUE TITLE
Considering a Sales Checklist

### ISSUE THREAD

**Issue by karllhughes** [karllhughes/side-project-marketing#37]
Based partly on feedback from readers and partly on my own assumptions, I'm thinking about creating a new checklist specifically for sales. Some thoughts/questions:

1. How would you differentiate between sales and marketing? (I think [this is a pretty good resource](http://www.diffen.com/difference/Marketing_vs_Sales), but what do you think?)

2. What tasks would you say are most crucial to sales?

3. Have you ever tried any unconventional sales tactics that worked?

4. What categories of tools are required for sales? Or is it just your own two feet?

**Comment by atherdon** [comment]
I like this tactic:
find a 150 places where you can gain a new users, deals, etc.
submit there at all places and see what place are more beneficial for your particular case
As we talking about side-projects, e.g. "startups" this can work for both(sales, marketing)

1. I think in small projects sales and marketing are synergy, inside owner's head.
2. Try, try, try?
3. Sure, but you always must to apply on numbers. So if you have some stupid idea, you need to do it **n** times and compare with **m**(more traditional way). Do you want examples?
4. You can do it with the list of paper if you want. For me, you need a tool, that you know how to use. so before you must to sell -> then you find out what you can improve -> find a tool that worked for you. in 90% cases I think google spreadsheet can be a choice

**Comment by karllhughes** [comment]
The sales checklist is in progress!

https://github.com/karllhughes/side-project-sales

I've actually got a decent first iteration up on this repo, but it's not quite ready for circulation yet. I need to integrate it into the website and clear out the sales-related tasks from the current marketing checklist.

**Comment by karllhughes** [comment]
The sales checklist is now live: https://www.sideprojectchecklist.com/sales-checklist/

and the repo here: https://github.com/karllhughes/side-project-sales

I'll be continuing to improve this list over the coming weeks, but for now will close this issue.
