### ISSUE TITLE
How to gain a first 100 users(maybe free)

### ISSUE THREAD

**Issue by atherdon** [karllhughes/side-project-marketing#41]
Sorry for making a mess on your issues, Karl.

But this is what is bothering me right now. 
I find a section on your checklist related to user acquisition.
But I want more ;) would you interested to chat in this comments? there is no rush, btw, it can wait

**Comment by karllhughes** [comment]
Yes of course.

Are you asking for an in-depth how to article that walks people through getting their first 100 users? I like the idea, but it's challenging because every product is different.

Also, do you want to explore paid users or free users? Free users is easy, but paid could be another story.

**Comment by atherdon** [comment]
Good!
Let's start from free users and maybe after this discussion you'll be able to extend that section.

For me, personally, articles not works well every time. If something will be really easy to use and push me forward - it'll be a winner. I read a lot of articles, but for this moment I don't use 80% bits of advice.  
Will prepare a list with articles and submit it to you soon.

Maybe I must specify more how I see this inside my head?

**Comment by karllhughes** [comment]
Yeah, I'm not 100% sure what you're envisioning, but I would welcome a guest post on this topic.

Speaking of this, I saw an article on Stripe's blog that is relevant to this discussion: https://stripe.com/atlas/guides/starting-sales

**Comment by atherdon** [comment]
Good article, but this not what i'm talking about. Web have a lot of tools/articles/hacks about growing, but we still have this problem. I mean do you know tool - that will push someone(like me) to grow this users database. Not by reading, but by doing simple steps, each day...

Btw, take a look on this repo. @LizaDziuba did a great job!
https://github.com/LisaDziuba/Marketing-for-Engineers

**Comment by karllhughes** [comment]
@atherdon, yeah I recently ran into that repo. Great list of resources.

To your point, you would like an app or service that pushed you to get your first 100 users? Maybe based on tactics in the side project checklist here?

I've had a couple requests for that. If you have any vision of what it might look like, let me know, I'm thinking of doing a prototype sometime.

**Comment by atherdon** [comment]
I think I know only two examples, that i'm ok with it, for this moment

- Ship from Product Hunt(paid option, because with free option you'll wait a lot of time) https://www.producthunt.com/ship
- Instaaa https://www.instaaa.com/

Will try both of this tools soon and will tell you about results.

P.S.maybe startup button can cover similar results, but I'm not sure: https://www.startupbutton.com/submit/
