### ISSUE TITLE
Improving tool voting and data

### ISSUE THREAD

**Issue by karllhughes** [karllhughes/side-project-marketing#42]
A few ideas were mentioned in [this PR](https://github.com/karllhughes/side-project-marketing/pull/40#issuecomment-338523098) so I wanted to open a new issue to discuss improvements in voting and the data we include in lists of tools.

Feel free to add ideas here.

**Comment by atherdon** [comment]
Do you have a single for products or there a few forms, each related to a different sections?

**Comment by karllhughes** [comment]
Just one form, but you can select a category: https://airtable.com/shrwrPOxd0wlqoiZb

If no category fits, you can just leave it blank and I'll add it later.

**Comment by atherdon** [comment]
gotcha

**Comment by atherdon** [comment]
I propose add to repo a  github issue template, where you'll be able to notify people about form submission.
Something like:

<!-- If you want to submit a new product, please go to .... ->
